### PR TITLE
Fix cppcheck error #1

### PR DESCRIPTION
**Pull request by IgorPolyakov**
Fixed memory leaks.

### CODE REVIEW

**Comment by IgorPolyakov** [comment]
Released version 2.2.16. gnubiff. Maybe we should remove the last change?

**Comment by zeldin** [comment]
> Released version 2.2.16. gnubiff. Maybe we should remove the last change?

Do you want to abandon this changeset and attempt a merge with upstreams instead?
(In that case I would suggest merging the master branch first, and then the xfce4 branch with that.)
Note that while they removed the leaky err_buf from socket.cc in 2.2.16, the failure to cleanup bin when result can not be allocated in decoding.cc is still there.

**Comment by zeldin** [comment]
On second though, I'd better do the merge since I have the CVS import...  :smile:

**Comment by zeldin** [comment]
Ok, here's the deal.  The only upstreams change that was not already included was a bunch of translation updates.  I have merged those.  The reason the leak in socket.cc is not in 2.2.16 is because it's in the TLS support code which was never backported to the 2.2 branch.

**Pull request closed without merging**
